### ISSUE TITLE
can u tell me how to use 4148/greenhat

### ISSUE THREAD

**Issue by Enolak** [StefanKrauth/C4CODATANotesExtractor#1]
some detail~ realwork.txt where i place?
and i run greenhat.py 365 2014-11-09
it can't work~~

**Comment by StefanKrauth** [comment]
Hi,
realowork.txt is created automatically. You can just do a git clone to download the repository (make sure you download using git and not using the https URL, so git push does not ask for a password).
Then just run ./greenhat.py <numberofdays>

**Comment by Enolak** [comment]
Can ...  the entire instruction process used to play it here ~~
and Remote repository to put things right?

**Comment by StefanKrauth** [comment]
You need to do this on the console:

```
git clone git@github.com:Enolak/greenhat.git
cd greenhat
python greenhat.py 356
```

However it is important that the repository is NOT a fork. So you would need to create a new repository with the files in your greenhat repository, adjust the commands above to point to your new repository. Please read [this document to learn why](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/).

**Comment by Enolak** [comment]
You are quite detailed, Can you give me please leave contact information(facebook or....)
I do not know convenient time to contact you, thx, I go to Study now

**Comment by StefanKrauth** [comment]
I'm not sure why you want to contact be, but my contact details are listed in my [Github Profile](https://github.com/StefanKrauth).

I'm closing this issue as you've opened it under the C4CODATANotesExtractor and not the greenhat repository.
